# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Mohamed Regaieg
title: Technical Director, Technical & Operational management
email: mohamed@regaieg.info
website: mohamed.regaieg.info

# Social links
# twitter_username: facespics
# github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: medregaieg
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/med.jpg
about_content: | # this will include new lines to allow paragraphs

Looking for leadership position in industrial field to enhance my career and bring out my skills to work in a continuous improvement process.

(Make it happen & team building attitude, <mark>kaizen</mark> and <mark>san-gen-shugi</mark> practices )

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in engineering and management, some of my other interests and hobbies are:
   - Hiking
   - Cooking
   - Reading
   - Travelling

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
